-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 18:04:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esquema_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esquema_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esquema_blog` DEFAULT CHARACTER SET utf8mb3 ;
USE `esquema_blog` ;

-- -----------------------------------------------------
-- Table `esquema_blog`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_blog`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `esquema_blog`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_blog`.`publicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicaciones_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `esquema_blog`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `esquema_blog`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_blog`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  `publicacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`publicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `esquema_blog`.`publicaciones` (`id`),
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `esquema_blog`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `esquema_blog`.`me_gusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_blog`.`me_gusta` (
  `usuario_id` INT NOT NULL,
  `publicacion_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `publicacion_id`),
  INDEX `fk_usuarios_has_publicaciones_publicaciones1_idx` (`publicacion_id` ASC) VISIBLE,
  INDEX `fk_usuarios_has_publicaciones_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_publicaciones_publicaciones1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `esquema_blog`.`publicaciones` (`id`),
  CONSTRAINT `fk_usuarios_has_publicaciones_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `esquema_blog`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
